### ISSUE TITLE
only black screen

### ISSUE THREAD

**Issue by legluondunet** [libretro/reicast-emulator#10]
Hello,

when I launch a Dreamcast game with Libretro Reicast core, I can hear DC bios music, but the screen is all black. Then nothing.

My config:

Ubuntu 15.10 Wily 64 bits
NVIDIA  GeForce GTX 770
official Ubuntu Nvidia drivers 352.63 resolution 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM
Retroarch/Libretro compiled from git 13/01/2016

The log: 

./retroarch
RetroArch [INFO] :: Config: loading config from: /home/legluondunet/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Threaded rarch_task started
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [INFO] :: [SDL]: Available renderers (change with $SDL_RENDER_DRIVER):
RetroArch [INFO] :: 	opengl
RetroArch [INFO] :: 	opengles2
RetroArch [INFO] :: 	software
RetroArch [INFO] :: [SDL]: Available displays:
RetroArch [INFO] :: 	Display #0 mode: 1920x1080@60hz.
RetroArch [INFO] :: [SDL]: Creating window @ 960x720
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event2 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event3 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event2 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/event3 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse1 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1729136759 (0x67108877)
 at -e line 15.
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/legluondunet/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [PulseAudio]: Pausing.
RetroArch [INFO] :: Using content: /home/legluondunet/Applications_persos/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi.
RetroArch [INFO] :: arg #0: retroarch
RetroArch [INFO] :: arg #1: /home/legluondunet/Applications_persos/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi
RetroArch [INFO] :: arg #2: -c
RetroArch [INFO] :: arg #3: /home/legluondunet/.config/retroarch/retroarch.cfg
RetroArch [INFO] :: arg #4: -L
RetroArch [INFO] :: arg #5: /home/legluondunet/Applications_persos/Jeux/Emulateurs/RetroArch/ra/cores/reicast_libretro.so
RetroArch [INFO] :: arg #6: -v
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES Built: Jan 13 2016
RetroArch [INFO] :: Version: 1.3.0
RetroArch [INFO] :: Git: 8fbd59b
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: Loading dynamic libretro core from: "/home/legluondunet/Applications_persos/Jeux/Emulateurs/RetroArch/ra13012016/cores/reicast_libretro.so"
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Environ GET_PERF_INTERFACE.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: XRGB8888.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: 	RetroPad, User 1, Button "B (bottom)" => "A"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Y (left)" => "X"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 1, Button "A (right)" => "B"
RetroArch [INFO] :: 	RetroPad, User 1, Button "X (up)" => "Y"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L" => "L (fierce)"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R" => "R (fierce)"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L2" => "L (weak)"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R2" => "R (weak)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "B (bottom)" => "A"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Y (left)" => "X"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 2, Button "A (right)" => "B"
RetroArch [INFO] :: 	RetroPad, User 2, Button "X (up)" => "Y"
RetroArch [INFO] :: 	RetroPad, User 2, Button "L" => "L (fierce)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "R" => "R (fierce)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "L2" => "L (weak)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "R2" => "R (weak)"
RetroArch [INFO] :: 	RetroPad, User 3, Button "B (bottom)" => "A"
RetroArch [INFO] :: 	RetroPad, User 3, Button "Y (left)" => "X"
RetroArch [INFO] :: 	RetroPad, User 3, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 3, Button "A (right)" => "B"
RetroArch [INFO] :: 	RetroPad, User 3, Button "X (up)" => "Y"
RetroArch [INFO] :: 	RetroPad, User 3, Button "L" => "L (fierce)"
RetroArch [INFO] :: 	RetroPad, User 3, Button "R" => "R (fierce)"
RetroArch [INFO] :: 	RetroPad, User 3, Button "L2" => "L (weak)"
RetroArch [INFO] :: 	RetroPad, User 3, Button "R2" => "R (weak)"
RetroArch [INFO] :: 	RetroPad, User 4, Button "B (bottom)" => "A"
RetroArch [INFO] :: 	RetroPad, User 4, Button "Y (left)" => "X"
RetroArch [INFO] :: 	RetroPad, User 4, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 4, Button "A (right)" => "B"
RetroArch [INFO] :: 	RetroPad, User 4, Button "X (up)" => "Y"
RetroArch [INFO] :: 	RetroPad, User 4, Button "L" => "L (fierce)"
RetroArch [INFO] :: 	RetroPad, User 4, Button "R" => "R (fierce)"
RetroArch [INFO] :: 	RetroPad, User 4, Button "L2" => "L (weak)"
RetroArch [INFO] :: 	RetroPad, User 4, Button "R2" => "R (weak)"
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/home/legluondunet/.config/retroarch/system/".
RetroArch [INFO] :: Environ GET_VARIABLE reicast_internal_resolution:
RetroArch [INFO] :: 	640x480
[reicast]: Got size: 640 x 480.
RetroArch [INFO] :: Environ GET_VARIABLE reicast_cpu_mode:
RetroArch [INFO] :: 	dynamic_recompiler
RetroArch [INFO] :: Environ GET_VARIABLE reicast_mipmapping:
RetroArch [INFO] :: RetroArch [INFO] :: Threaded rarch_task started
	enabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_widescreen_hack:
RetroArch [INFO] :: 	disabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_audio_buffer_size:
RetroArch [INFO] :: 	1024
RetroArch [INFO] :: Environ GET_VARIABLE reicast_cable_type:
RetroArch [INFO] :: 	TV (VBS/Y+S/C)
RetroArch [INFO] :: Environ GET_VARIABLE reicast_precompile_shaders:
RetroArch [INFO] :: 	disabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_enable_rtt:
RetroArch [INFO] :: 	enabled
RetroArch [INFO] :: Environ SET_HW_RENDER.
RetroArch [INFO] :: Requesting OpenGL context.
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
RetroArch [INFO] :: Video @ 1920x1440
RetroArch [INFO] :: Using HW render, OpenGL driver forced.
RetroArch [INFO] :: Found GL context: glx
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 1920, H = 1440.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalEXT.
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 770/PCIe/SSE2.
RetroArch [INFO] :: [GL]: Version: 4.5.0 NVIDIA 352.63.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 1920x1016
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Not loading any shader.
RetroArch [INFO] :: [GL]: Using 1 textures.
RetroArch [INFO] :: [GL]: Loaded 0 program(s).
RetroArch [INFO] :: [GL]: Initializing HW render (1024 x 1024).
RetroArch [INFO] :: [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
context_reset.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1729136742 (0x67108866)
 at -e line 15.
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: null: [/home/legluondunet/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 139F0000, aram: 339f0000, vram: 179F0000, ram: 1F9F0000
Resetting mem
Mem alloc successful!Loaded /home/legluondunet/.config/retroarch/system//dc/dc_boot.bin as bootrom

Loaded /home/legluondunet/.config/retroarch/system//dc/dc_flash.bin as nvram

Using Recompiler
Sh4 Reset
recSh4 Init
@@	ngen_ResetBlocks()
Freeing fpcb

	 CodeCache addr: 0x7fc93a4e6000 | from: 0x7fc93a4e6000 | addr here: 0x7fc93a4e53a0

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 302     LBA: 0       
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 309642  LBA: 11702   
Track position: 1413504
gdrom: Opened image "/home/legluondunet/Applications_persos/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi"
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISESAD31 GD-ROM1/1  JUE     0799A10 MK-51035  V1.00020000120        1ST_READ.BIN    ECHELON         CRAZY TAXI                                                                                                                      @��;�'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: AD31 GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 0799A10 
reios: Product number is: MK-51035  
reios: Product version is: V1.000
reios: Release date is: 20000120        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: ECHELON         
reios: Software name is: CRAZY TAXI                                                                                                                      
reios: loading ip.bin from FAD: 11852
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11875, len: 4096
Found 1ST_READ.BIN at 0000B9
filename len: 14
file LBA: 268072
file LEN: 1477040
cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Sh4: i-cache invalidation A0000016
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at A0000016
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C0000DE
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
SPI : unknown ? [0x70]
SPI : unknown ? [0x71]
sh4io: Invalid read access @@ 00000030
Sh4: i-cache invalidation 8C00DD78
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
Sh4: i-cache invalidation 8C09E6A6
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
new tactx
new tactx
FOG TABLE Curve match: maxdev: 0.43 cents
SPI : unknown ? [0x70]
SPI : unknown ? [0x71]
RetroArch [INFO] :: Average audio buffer saturation: 80.28 %, standard deviation (percentage points): 12.13 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 0.11 %. Close to blocking: 60.82 %.
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [X11]: Saved monitor #0.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: [SDL]: Available renderers (change with $SDL_RENDER_DRIVER):
RetroArch [INFO] :: 	opengl
RetroArch [INFO] :: 	opengles2
RetroArch [INFO] :: 	software
RetroArch [INFO] :: [SDL]: Available displays:
RetroArch [INFO] :: 	Display #0 mode: 1920x1080@60hz.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1729136768 (0x67108880)
 at -e line 15.
Sh4: i-cache invalidation AC09EC6E
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09EC6E
Sh4: i-cache invalidation 8C00DD78
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
Sh4: i-cache invalidation 8C09E6A6
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
@@	ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
RetroArch [INFO] :: Average audio buffer saturation: 76.95 %, standard deviation (percentage points): 14.97 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 0.61 %. Close to blocking: 56.71 %.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
RetroArch [INFO] :: Video @ 1920x1440
RetroArch [INFO] :: [SDL]: Available renderers (change with $SDL_RENDER_DRIVER):
RetroArch [INFO] :: 	opengl
RetroArch [INFO] :: 	opengles2
RetroArch [INFO] :: 	software
RetroArch [INFO] :: [SDL]: Available displays:
RetroArch [INFO] :: 	Display #0 mode: 1920x1080@60hz.
RetroArch [INFO] :: [SDL]: Creating window @ 1920x1440
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1729136759 (0x67108877)
 at -e line 15.
RetroArch [INFO] :: [PulseAudio]: Underrun (Buffer: 18432, Writable size: 9512).
RetroArch [INFO] :: [PulseAudio]: Got new buffer size 22272.
RetroArch [INFO] :: [PulseAudio]: Underrun (Buffer: 22272, Writable size: 17792).
RetroArch [INFO] :: [PulseAudio]: Underrun (Buffer: 22272, Writable size: 17792).
RetroArch [INFO] :: [PulseAudio]: Underrun (Buffer: 22272, Writable size: 17800).
RetroArch [INFO] :: [PulseAudio]: Underrun (Buffer: 22272, Writable size: 17800).

**Comment by fr500** [comment]
go to settings/core and enable shared context

**Comment by legluondunet** [comment]
It works now, thank you.
But could you tell me why I have to enable this option for Reicast and not for the others cores?
