### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Shoegzer** [libretro/reicast-emulator#12]
Two feature requests:

1) Support for Broadcast/Region configuration via the RA UI. Standalone Reicast emu.cfg shows two settings not reflected in the RA core: Dreamcast.Broadcast (defaults to 4) and Dreamcast.Region (defaults to 3).  While I'm not clear on what these values actually map to (nor is skmp apparently), they make a difference to some games (especially the latter).

2) Support for boot-to-bios. Currently there is no way to boot into the DC bios without booting an invalid game disc, which is not exactly intuitive.  Booting to bios is an important option on the real DC as it permits configuring the VMU, clock etc.  I'm thinking this could be implemented as something along the lines of "Load Content > Boot to BIOS" though perhaps there's a better way.

Incidentally, this would be a nice feature for the mednafen-psx core too, and perhaps others?

Thanks.

**Comment by twinaphex** [comment]
1) Took care of the first two.
2) Will have to research it.

**Comment by Shoegzer** [comment]
Thanks again.  

On 1), There's an issue - in the GUI, the word "Region" appears twice.  I believe this is due to line 173, [here] (https://github.com/libretro/reicast-emulator/commit/413a28ca8554a5cd4f1486bbd1fc69f57b6d5b29):

+         "Region; 0|1|2|3|4",
...should probably be:
+         "Broadcast; 0|1|2|3|4",

On 2) regarding boot-to-bios: no worries, it will be great when it happens but take your time.

**Comment by Shoegzer** [comment]
Closing this now as both features are there... thanks again.
