### ISSUE TITLE
Sturmwind hangs on pressing "start" ingame

### ISSUE THREAD

**Issue by Shoegzer** [libretro/reicast-emulator#13]
The game "Sturmwind" hangs when you press the start button ingame.  It will show the pause menu, but you can't escape back to the game after that.  Since pressing start is required to progress through the levels, this effectively renders the game unplayable.  

A few items to note:

1) Tested with a clean RA configuration, on a build of RA from Jan. 23 2016
2) Issue does not occur in standalone Reicast, on a build from Jan. 23 2016
3) Start button does not hang the RA core when you press it to bypass the "swirl" bootup logo, but then stops working properly in the game itself
4) I noticed the RA reicast core creates eight VMU save files (A1-D2); however standalone creates only two (A1-A2).  Perhaps this indicates too many input devices plugged in, but haven't tried to reduce them yet.  Not sure if this is a clue, but maybe worth looking into.

**Comment by heuripedes** [comment]
Quote from my commit:
> The problem happened because control flow never returned to retro_run()
> so poll_cb() was never called. Moving the call to os_DoEvents() fixes
> the issue but requires RetroArch's "Input > Poll Type Behavior" set to
> "Normal" so that poll_cb() isn't a no-op.

I don't know if it's the optimal solution, but seemed to work well. It'd be cool if you could review it @twinaphex

**Comment by twinaphex** [comment]
How would we go about fixing this for the other two poll type behavior options.

**Comment by heuripedes** [comment]
From the reicast side I've no idea at all, but regarding libretro I think returning to the main thread - `retro_run()` in this case - *could* work.
