### ISSUE TITLE
Fail to load to BIOS

### ISSUE THREAD

**Issue by ofry** [libretro/reicast-emulator#27]
If I checked flag "boot to BIOS" and try to run ROM, Retroarch.exe crashes immediately.

Log is there:
https://dl.dropboxusercontent.com/u/97349870/retro-reicast-fail_boot_to_bios-07.05.2016.txt

**Comment by RobLoach** [comment]
Where'd you place the BIOS files?
https://wiki.libretro.com/index.php?title=Reicast#BIOS

**Comment by ofry** [comment]
Yes, I placed it there.

In "core information" dc_boot.bin and dc_flash.bin shown as "Present, required".

**Comment by ofry** [comment]
New log:

https://dl.dropboxusercontent.com/u/97349870/retro-reicast-fail_boot_to_bios-18.07.2016_v2.txt

**Comment by ofry** [comment]
That bug has fixed now. I'm close this issue.
