### ISSUE TITLE
(Regression) Soul Calibur segfaults when starting with nouveau

### ISSUE THREAD

**Issue by orbea** [libretro/reicast-emulator#35]
OS: `Slackware64-current`
`RetroArch-2016.10.17_affd603_master-x86_64-1_git`

The game Soul Calibur will now segfault when starting.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffeab17c7e in ngen_mainloop (v_cntx=0x7fffbf650000)
    at core/hw/sh4/dyna/driver.cpp:92
92	         DynarecCodeEntryPtr rcb = (DynarecCodeEntryPtr)FPCA(ctx->cntx.pc);
```
gdb log - http://pastebin.com/UrE9Smsc

The first bad commit was.
```
$ git bisect bad
3b36f7c6aeab23d1e8a6240decc708c203003faf is the first bad commit
commit 3b36f7c6aeab23d1e8a6240decc708c203003faf
Author: twinaphex <libretro@gmail.com>
Date:   Fri Sep 16 03:18:34 2016 +0200

    Update glsm

:040000 040000 6ba7b27b4d3cb687e584de306f2d1c494e8ee560 6d42e2fd30b3376a06348b1ab36df455166a7056 M	core
```
https://github.com/libretro/reicast-emulator/commit/3b36f7c6aeab23d1e8a6240decc708c203003faf

**Comment by orbea** [comment]
Removing these lines will work around the segfault, however there might be a better solution?
```
+
+      if (gl_state.attrib_pointer.used[i])
+      {
+         glVertexAttribPointer(
+               i,
+               gl_state.attrib_pointer.size[i],
+               gl_state.attrib_pointer.type[i],
+               gl_state.attrib_pointer.normalized[i],
+               gl_state.attrib_pointer.stride[i],
+               gl_state.attrib_pointer.pointer[i]);
+      }
```

**Comment by orbea** [comment]
The rom's md5sum is `03ded9f61e45498565f409255c5d7df0  Soul Calibur.cdi`

**Comment by orbea** [comment]
This is probably not the rom itself, I've tried too additional versions which show the same issue.
```
ae14de6a8f30e203bbbf0bda13152269  2003-11-19-Soul-Calibur-DCP.cdi
678b4402871c84e60d1701641e5958f3  2004-01-30-Soul-Calibur-Pal-DCP.cdi
```

**Comment by twinaphex** [comment]
Doesn't happen here.

**Comment by orbea** [comment]
This is probably related to the nouveau drivers. `LIBGL_ALWAYS_SOFTWARE=1` works around it but is of course very slow. I will have to recompile mesa with the llvmpipe to try that too.

**Comment by orbea** [comment]
llvmpipe will segfault too. I guess this is not nouveau, but could be gallium rather than mesa if intel works for @twinaphex?

**Comment by orbea** [comment]
Alright, I figured how to use the llvmpipe correctly... Both the llvmpipe and softpipe will work with this game, so its probably only nouveau that has a problem here.

**Comment by orbea** [comment]
Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/reicast_crash.trace.xz
Log - http://pastebin.com/JEhLXZiJ
Valgrind log - http://pastebin.com/hmRRCFsf

**Comment by imirkin** [comment]
(nouveau dev here)

Observation: glsm_state_bind first calls enable/disable array + glVertexAttribPointer, and *then* calls glBindVertexArray(gl_state.vao);

This seems odd. But I don't know the flow of things.

**Comment by orbea** [comment]
Here is some relevent discussion on this issue in #nouveau.
```
21:20 <orbea> im having an intersting segfault/regression in the libretro port of reicast (Dreamcast emulator), the problem is that is only seems to occur with nouveau. I could not reproduce it with intel or the llvmpipe. I found the code bit of code that was causing problems, but I'm not really sure why. Backtrace: http://pastebin.com/UrE9Smsc Bad commit in reicast:
21:20 <orbea> https://github.com/libretro/reicast-emulator/commit/3b36f7c6aeab23d1e8a6240decc708c203003faf github issue: https://github.com/libretro/reicast-emulator/issues/35
21:21 <imirkin> ooooh, soul calibur. good times.
21:21 <orbea> yea, its still fun
21:22 <imirkin> is there a non-jit backend you can switch to?
21:22 <imirkin> or, better idea
21:22 <imirkin> make an apitrace
21:22 <orbea> sure, let me try both
21:22 <imirkin> and then replay it with valgrind
21:23 <imirkin> basically the crash is in not-nouveau
21:23 <orbea> reicast is in a really messy state and it probabl something there
21:23 <imirkin> so that suggests that nouveau stomps over something (or something stomps over nouveau)
21:23 <imirkin> normally emulator + valgrind = fail
21:25 <imirkin> orbea: are you running this with a core context, or not?
21:25 <imirkin> i.e. is the #ifdef CORE thing on?
21:25 <orbea> i think its a core context
21:26 <orbea> it doesn't black screen and should use some opengl 4.*
21:26 <imirkin> anyways ... i guess i'm not sure offhand what the issue is
21:26 <orbea> i'll add more info with the apitrace in a little bit
21:26 <imirkin> it's entirely possible it's an issue in nouveau
21:27 <orbea> i think twinaphex is willing to fix it, but he has an intel gpu and ofc cant reproduce it...
21:28 <imirkin> uhm
21:28 <imirkin> it's odd that they do glBindVertexArray(gl_state.vao); *before* all the glVertexAttribPointer calls
21:28 <imirkin> but i'm a bit weak on VAO's & co
21:29 <imirkin> try moving that up to the top of the function
21:29 <orbea> the story is the original reicast dev did a half assed job and then abandoned it when he realized no one was going to pay him anything....kind of left other people to clean it up...
21:30 <ystreet00> vao's need to be bound before vertexattrib (otherwise they don't affect anything)
21:30 <imirkin> orbea: sklm or whatever that guy's handle was?
21:30 <ystreet00> and in core you need a vao to be able to vertexattrib
21:30 <imirkin> definitely an s and k somewhere in there
21:31 <orbea> imirkin: yea, something liek that
21:33 <orbea> apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/reicast_crash.trace.xz valgring log output - http://pastebin.com/hmRRCFsf
21:34 <imirkin> orbea: ok, so no access errors
21:35 <orbea> crashes with without the generic jit, but that is on by default, so Im not sure how useful reciast is / was without it
21:35 <imirkin> what if you move the glBindVertexArray to the top of the function?
21:44 <orbea> If I did it rightthat didn't really work.
```
@twinaphex Does any of this help you understand the issue more?

**Comment by twinaphex** [comment]
Previously reicast required core context but it no longer does, I am not even sure why it was attempted since the GL renderer still self limits itself to a GLES2 featureset, so apart from generating a VAO and binding/unbinding it, it didnt really do anything extra.

It could be possible that the GL state machine (GLSM) has regressed leading to the issues you are describing with Nouveau. @loganmc10 Any input here since AFAIK this change to GLSM was something you introduced? Anything you could think of that would cause this regression with Nouveau but not Intel Mesa?

**Comment by imirkin** [comment]
Intel (i965) is not a gallium backend driver, and has their own logic for processing GL calls (sorta, there's a shared core which does some stuff, and a shared vbo module which does other stuff). All gallium-based drivers (nouveau, radeonsi, llvmpipe, and many others) share a converter between GL craziness to something much closer to what HW wants to see (i.e. the gallium API). However orbea mentioned that llvmpipe worked, but a comparison to radeonsi would probably be much closer.

The idea of a non-JIT backend was to run valgrind on the application to see if anything popped up. However emulators tend to be pretty valgrind-unfriendly. That was the only reason for the idea.

**Comment by orbea** [comment]
For what's its worth here are some logs with `make HAVE_GENERIC_JIT=0`.

gdb log - http://pastebin.com/mx0r0R6V
valgrind log of replaying an apitrace - http://pastebin.com/QU2ztfYq

**Comment by orbea** [comment]
I've tried another games, Skies of Arcadia, where this also occurs.

**Comment by loganmc10** [comment]
I'll look at this this afternoon (about 7-8 houra from now), I'm fairly confident I can fix this by tracking the state of GL_ARRAY_BUFFER. I haven't looked at the apitrace, but I assume this is probably happening because glVertexAttribPointer is being called without the right GL_ARRAY_BUFFER being bound first

**Comment by loganmc10** [comment]
@orbea I submitted a pull request that @twinaphex just merged that should hopefully fix the issue, but haven't tested it or anything, it is just based on my understanding on how these calls should flow.

**Comment by loganmc10** [comment]
or maybe it got reverted (it should be tested first), but if you try commit 80a0489515bf1760044e26d833ebf7f266d8f653 that should let you know if it fixed it

**Comment by twinaphex** [comment]
Yeah you could try that commit.

Sorry BTW that I merged immediately before reading your commit message that we should hold off until @orbea tested it.

**Comment by orbea** [comment]
@loganmc10 @twinaphex  That was enough to avoid the segfault, thanks!

**Comment by loganmc10** [comment]
@twinaphex Can you revert the revert? It won't let me re-send the same thing in a pull request since it thinks the commit is already part of the repo.

**Comment by twinaphex** [comment]
That's great to hear that it fixed it.
