### ISSUE TITLE
Core crash at startup

### ISSUE THREAD

**Issue by mac1202** [libretro/reicast-emulator#9]
Hi, i got a crash with this core at startup, here is the terminal output : 
    
    Linux paging: 00001000 00001000 00000FFF
    RetroArch [libretro INFO] ::  :: Verify Failed  : ftruncate(fd,RAM_SIZE 
    + VRAM_SIZE +ARAM_SIZE)==0
     in _nvmem_alloc_mem -> core/hw/mem/_vmem.cpp : 591 
    DEBUGBREAK!

If it's too soon to report bug just ignore it and close the report.

**Comment by twinaphex** [comment]
which platform?

Are you sure your system directory is writable? It needs to be otherwise it won't work.

**Comment by mac1202** [comment]
I m on manjaro linux.
Yes system directory is writable.

**Comment by elsonrodriguez** [comment]
I got messages like this when I didn't have the DC firmware in the right place, can you verify in RetroArch that the core reports the files as present?

**Comment by mac1202** [comment]
retroarch doesnt start at all, and i got no message in console about bios files even with verbose output

**Comment by elsonrodriguez** [comment]
I had to put mine in System/dc/

Try to verify this by starting retroarch with no options, then loading the core from within the GUI.

**Comment by mac1202** [comment]
thanks that solve my problem, bios should be in a dc folder
